version: "3.9"


networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1


services:
  mongodb:
    image : mongo
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    networks:
      default:
        ipv4_address: 172.22.0.6
    restart: unless-stopped
